maintainer       "EMC Corporation"
maintainer_email "joe.fitzgerald@emc.com"
license          "Apache 2.0"
description      "Installs/Configures PSTools (http://technet.microsoft.com/en-us/sysinternals/bb896649)"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0.0"
supports         "windows"
depends          "windows", ">= 1.3.0"
depends          "powershell", ">= 1.0.6"
depends          "7-zip", ">= 1.0.0"
